export const USER_LOGION_REQUEST = 'USER_LOGION_REQUEST';
export const USER_LOGION_SUCCESS = 'USER_LOGION_SUCCESS';
export const USER_LOGION_FAIL = 'USER_LOGION_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
